
name: Upload classes action
on: 
  workflow_dispatch:
  schedule:
    # Runs every day at 23:15 pm CST (5:15 am UTC)
    - cron: '15 5 * * *'
env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: ${{ secrets.DB_HOST }}
  VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
  VIMEO_TOKEN_SECONDARY: ${{ secrets.VIMEO_TOKEN_SECONDARY }}

jobs:
  upload-classes:
    name: Upload classes
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: 'Install'
        run: npm install

      - name: 'Upload classes from primary vimeo account'
        run: npm run tools:classes:last

      - name: Slack Notification Failure
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.19.0
        with: 
          channel-id: 'C027DB3QK1N' ##grabaciones
          slack-message: ':alert: Oops! La carga de clases ha tenido un problema: ${{ job.status }}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.19.0
        with: 
          channel-id: 'C027DB3QK1N' ##grabaciones
          slack-message: ':rocket: Las clases de hoy han sido cargadas exitosamente'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: 'Upload classes from secondary vimeo account'  
        run: npm run tools:classes:last -- --use-secondary

